
POST http://localhost:5000/create-video
Content-Type: application/json
x-api-key: abc

{
    "record_id": "12345",
  "input_url": "http://localhost:5500/assets/puppy.jpg",
  "framerate": 24,
  "duration": 48,
  "cache": true,
  "zoom": 1.0,
  "crop": "true",
  "output_width": 1920,
  "output_height": 1080,
  "webhook_url": "http://localhost/webhook"
}
